baseURL = "https://peterboshe.netlify.app/"
title = "Peter Boshe"
subtitle = "This is Peter's online data science portfolio."
description = "I enjoy tackling real world problems with **data analysis** and **machine learning**. I specialize in building data products, reports and facilitating data-driven decisions using R."
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-217879983-1"
googleAnalyticsID = "G-6Q7BSBKL74"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
summaryLength = 25
canonifyURLs = true
relativeURLs = true
enableEmoji = true
uglyURLs = false
permalinks = "https://peterboshe.netlify.app/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "sample-dashboard"
    name = "Sample Dashboard"
    url = "https://petertoc.github.io/flexdashboard/"
    weight = 0
  [[menu.main]]
    identifier = "sample-dashboard"
    name = "Sample Dashboard"
    url = "https://petertoc.github.io/flexdashboard/"
    weight = 0
  [[menu.main]]
    identifier = "sample-reports"
    name = "Sample Reports"
    url = "https://rpubs.com/Peter_Beta/"
    weight = 0
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  title = "Welcome to my<br>data science portfolio."
  description = "I enjoy tackling real world <br>problems with data analysis and <br>machine learning. I specialize in building <br>data products, reports and facilitating <br>data-driven decisions using R. <br><br>Below are some of the recent posts I have published."
  images = "/static/images/webteatheme3.png"
  homepageImage = "/images/webteatheme3.png"
  dateFormat = "January 2, 2006"
  share = true
  showLanguageSwitcher = false
  googleTagManager = "GTM-TRR9NK9"
  subtitle = "Data Analyst"

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["style1.css"]
  customJS = ["web-tea/themes/hugo-theme-chunky-poster/src/main.js"]

  [params.social]
    rss = true
    email = "peterboshe@gmail.com"
    linkedin = "https://www.linkedin.com/in/peterboshe/"
    stack-overflow = "https://stackoverflow.com/users/15254380/peter"
    github = "https://github.com/PeterTOC"
    upwork = "https://www.upwork.com/freelancers/~01ccb5205045cae5f6"
    reddit = "https://www.reddit.com/user/Traditional_Net9757/"
    

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
  [services.instagram]
    disableInlineCSS = true
    accessToken = "aaaa"

  [services.twitter]
    disableInlineCSS = true
