baseURL = "/"
title = "Peter Boshe"
description = "This is Peter Boshe's Data Science Portfolio, Look Around."
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-217879983-1"
googleAnalyticsID = "G-6Q7BSBKL74"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
summaryLength = 25
canonifyURLs = true
enableEmoji = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
author = "authors"

[params]
  author = "Peter Boshe"
  description = "This is my Data Science Portfolio, <br> Look around."
  images = "/static/images/webteatheme3.png"
  homepageImage = "/images/webteatheme3.png"
  dateFormat = "January 2, 2006"
  share = true
  showLanguageSwitcher = false
  googleTagManager = "GTM-TRR9NK9"

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = ["style1.css"]
  customJS = ["web-tea/themes/hugo-theme-chunky-poster/src/main.js"]

  [params.social]
    rss = true
    email = "peterboshe@gmail.com"
    linkedin = "https://www.linkedin.com/in/peterboshe/"
    stack-overflow = "https://stackoverflow.com/users/15254380/peter"
    github = "https://github.com/PeterTOC"
    upwork = "https://www.upwork.com/freelancers/~01ccb5205045cae5f6"
    reddit = "https://www.reddit.com/user/Traditional_Net9757/"
    

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
  [services.instagram]
    disableInlineCSS = true
    accessToken = "aaaa"

  [services.twitter]
    disableInlineCSS = true
