---
title: 'Tanzania Mainland Football Championships: 1965 - 2020'
author: 'Peter Boshe'
date: '2021-10-19'
categories: ["Sports"]
tags: ["DataViz", "Unguided project"]
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
images: []
summary: "This is a racing bar chart of the male football championships and the respective teams that have won over the past half century"
draft: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = 'center', collapse = TRUE)
```
This is a racing bar chart of the championships and the respective teams that have won over the past half century(acc. to [Data](http://www.rsssf.com/tablest/tanzchamp.html)),

Would you have guessed that less than 10 teams (only 9 teams) have won since the conception of the cup?


## setting up the environment
```{r environment, warning=FALSE, message=FALSE}
# clear environment 
rm(list = ls())

# setting environment 
library(readxl)
library(tidyverse)
library(gganimate)
library(lubridate)

# loading data 
df <- read_excel("Tanzania mainland championships.xlsx")

```

## inspecting the dataset

```{r inspection}
skimr::skim(df)
```
## create the racing bar chart


Note: data with incomplete detail was removed
```{r main code}
data_df <- df %>% 
  select(Team, Year) %>% 
  group_by(Team) %>% 
  mutate(cups = 1:n())  %>% 
  # mutate(rank = 1:n())  %>% 
  # pivot_wider(names_from = "Year", values_from = "cups") %>% 
  # pivot
  ungroup() %>% 
  group_by(Year) %>% 
  arrange(-cups) %>% 
  ggplot(aes(x = cups, y = Team, group = Team,
             fill = as.factor(Team))) +
  geom_col() +
  # geom_rect(aes(xmin = 0, 
  #               xmax = cups,
  #               ymin = Team[cups > 0] ,
  #               ymax = Team[cups > 0],
  #               y = Team[cups > 0]))+
  facet_wrap(~ Year) +
  scale_x_continuous(limits = c(0,30),
                     breaks = 1:30) +
  ggtitle("Mainland Championships since inception") +
  labs(x = "Cups") +
  labs(y = "Teams that have won") +
  labs(fill = NULL) +
  theme_classic() +
  facet_null() +
  geom_text(col = "darkblue", size = 12,
            aes(group = Team, label = as.character(Year), x = 27, y = 3 )) +
  transition_time(Year)

```

```{r}
 df1 <- df %>% 
     group_by(Team) %>% 
     mutate(cups = 1:n()) %>% 
     ungroup() %>% 
     group_by(Year) %>% 
     spread(Year, cups) %>% 
     replace(is.na(.),0) %>% #need to find way to carry over counts
  pivot_longer(-Team) %>% 
  mutate(rank = min_rank(-value) * 1) %>% 
  ungroup()
https://stackoverflow.com/questions/1699046/for-each-row-in-an-r-dataframe
```




```{r}
p <- ggplot(data = df1, 
            aes(rank, 
                group = Team, 
                fill = as.factor(Team), 
                color = as.factor(Team))) +
    geom_tile(aes(y = value/2, 
                  height = value, 
                  width = 0.9), 
              alpha = 0.8, color = NA) +
    
     # text in x-axis (requires clip = "off" in coord_*)
     # paste(country, " ")  is a hack to make pretty spacing, since hjust > 1 
    #   leads to weird artifacts in text spacing.
    geom_text(aes(y = 0, 
                  label = paste(Team, " ")), 
              vjust = 0.2, 
              hjust = 1) +
    coord_flip(clip = "off", expand = FALSE) +
    scale_y_continuous(labels = scales::comma) +
    scale_x_reverse() +
    guides(color = FALSE, fill = FALSE) +
    labs(title='Mainland Championship', 
         x = "", 
         y = "value") +
    theme(plot.title = element_text(hjust = 0, 
                                    size = 22),
          axis.ticks.y = element_blank(),  # These relate to the axes post-flip
          axis.text.y  = element_blank(),  # These relate to the axes post-flip
          plot.margin = margin(1,1,1,4, "cm")) +
  
     transition_states(name, transition_length = 4, state_length = 1) +
     ease_aes('cubic-in-out')

animate(p, fps = 55, duration = 55, width = 800, height = 600)

```

